# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release Tag

on:
  push:
    branches: ['tag']

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Get version
        id: get-version
        run: |
          VERSION=$(cd packages/qui-core && node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT
        shell: bash

  create-tag:
    permissions:
      contents: write # to create tag
    runs-on: ubuntu-latest
    needs: ['check-version']
    if: ${{ needs.check-version.outputs.version != '' }}
    outputs:
      tag-exists: ${{ steps.create-tag.outputs.tag_exists }}
      release-body: ${{ steps.generate-body.outputs.body }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Generate body
        id: generate-body
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          git_logs=$(git log "$(git describe --tags --abbrev=0)"..HEAD --oneline)
          git_logs="${git_logs//$'\n'/$'\n'- }"
          {
              echo "body<<$EOF"
              echo "- $git_logs"
              echo "$EOF"
          } >>"$GITHUB_OUTPUT"
        shell: bash
      - uses: rickstaa/action-create-tag@v1
        id: create-tag
        with:
          tag: ${{ needs.check-version.outputs.version }}
          tag_exists_error: false
          message: ${{ needs.check-version.outputs.version }}

  create-release:
    permissions:
      contents: write # to create release
    runs-on: ubuntu-latest
    needs: ['check-version', 'create-tag']
    if: ${{ needs.create-tag.outputs.tag-exists == 'false' }}
    steps:
      - uses: actions/checkout@v3
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.check-version.outputs.version }}
          name: ${{ needs.check-version.outputs.version }}
          body: ${{ needs.create-tag.outputs.release-body }}
